# services:
#   web:
#     build: .
#     volumes:
#       - .:/code
#   web_migrate:
#     extends:
#       service: web
#     command: python /code/myshop/manage.py migrate
#   web_run:
#     extends:
#       service: web
#     command: python /code/myshop/manage.py runserver 0.0.0.0:8000
#     ports:
#       - "8000:8000"
#     depends_on:
#       - web_migrate

version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13.1-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped


  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server
    restart: unless-stopped

